### ISSUE TITLE
Signal hierarchy trace look blurred on macOS

### ISSUE THREAD

**Issue by kammoh** [toem/impulse.vscode#3] opened 2021-09-17 17:09 UTC
As seen on this screenshot, text and graphics on the left hand side look good, but the hierarchy tree on the right hand side ad the traces look blurry.
It can cause a lot of eye fatigue if you have to go through the traces for a while!

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1421056/133826856-3dfb1dde-6d1a-4642-9e97-554b238d12d3.png">

Tried on macOS Big Sur (11.6), vscode 1.60.1, openjdk 11.0.12

**Comment by thomasAtToem** [comment] 2021-09-18 16:20
YEs, currently only 100% zoom is supported.
You may change  by using ctrl +/-.
Will be fixed soon.

**Comment by kammoh** [comment] 2021-09-18 17:35
The blurring exists even on 100% (no zoom).

**Comment by thomasAtToem** [comment] 2021-10-27 14:50
Hi, we updated to 0.3.0 and modified the zoom behaviour - the canvas geometry is always display compatible . Good chance that the issue is fixed.

**Closed as completed** 2022-02-02 11:40 UTC
